version: '3.8'

services:
  app:
    build: .
    container_name: user-api
    depends_on:
      - db
      - rabbitmq
      - mailer
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: npm run start:prod
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lms_bot
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  mailer:
    image: mailhog/mailhog
    container_name: user-mailer
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  postgres_data:
